version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: playsms
      DB_PASS: playsms
      DB_NAME: playsms
  db:
    image: mariadb:10.7.3
    restart: always
    environment:
      MARIADB_DATABASE: playsms
      MARIADB_USER: playsms
      MARIADB_PASSWORD: playsms
      MARIADB_ROOT_PASSWORD: playsms
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
